server:
  port: 8201
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true #使用小写service-id
      routes: #配置路由路径
        - id: kirito-auth
          uri: lb://kirito-auth
          predicates:
            - Path=/kirito-auth/**
          filters:
            - StripPrefix=1
        - id: kirito-admin
          uri: lb://kirito-admin
          predicates:
            - Path=/kirito-admin/**
          filters:
            - StripPrefix=1
        - id: kirito-portal
          uri: lb://kirito-portal
          predicates:
            - Path=/kirito-portal/**
          filters:
            - StripPrefix=1
        - id: kirito-search
          uri: lb://kirito-search
          predicates:
            - Path=/kirito-search/**
          filters:
            - StripPrefix=1
        - id: kirito-demo
          uri: lb://kirito-demo
          predicates:
            - Path=/kirito-demo/**
          filters:
            - StripPrefix=1

secure:
  ignore:
    urls: #配置白名单路径
      - "/doc.html"
      - "/swagger-resources/**"
      - "/swagger/**"
      - "/**/v2/api-docs"
      - "/**/*.js"
      - "/**/*.css"
      - "/**/*.png"
      - "/**/*.ico"
      - "/webjars/springfox-swagger-ui/**"
      - "/actuator/**"
      - "/kirito-auth/oauth/token"
      - "/kirito-auth/rsa/publicKey"
      - "/kirito-search/**"
      - "/kirito-portal/sso/login"
      - "/kirito-portal/sso/register"
      - "/kirito-portal/sso/getAuthCode"
      - "/kirito-portal/home/**"
      - "/kirito-portal/product/**"
      - "/kirito-portal/brand/**"
      - "/kirito-admin/admin/login"
      - "/kirito-admin/admin/register"
management: #开启SpringBoot Admin的监控
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
