server:
  port: 7001

spring:
  application:
    name: nacos-portal-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

management:
  endpoints:
    web:
      exposure:
        include: '*'

# server-list
server-url:
  nacos-sso-service: http://nacos-sso-service