server:
  port: 7001

spring:
  profiles:
    active: local
  application:
    name: nacos-portal-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

management:
  endpoints:
    web:
      exposure:
        include: '*'

# mybatis
mybatis:
  mapper-locations: classpath*:portal/*.xml
  type-aliases-package: com.kirito.cloud.portal.model

# server-list
server-url:
  nacos-sso-service: http://nacos-sso-service